version: '3'
services:
    app:
        build:
            context: ./
        volumes:
            -   .:/var/www
        ports:
            -   "8080:8080"
        environment:
            - APP_ENV=local
        links:
            -   mysql
    mysql:
        platform: linux/x86_64
        image: mysql:5.7
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: hD5rC2ccAq
    adminer:
        image: adminer
        restart: always
        ports:
            - "8081:8080"
