version: '3'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /var/www/html
        depends_on:
            -   mysql
        ports:
            -   "8080:8080"
        volumes:
            -   .:/var/www/html
            - ./docker/nginx_log:/var/log/nginx
            - ./docker/php-fpm/php-fpm.log:/var/log/php-fpm.log
            - ./docker/config/app.conf:/etc/nginx/conf.d/app.conf
        links:
            -   mysql
        environment:
            - APP_ENV=local
    mysql:
        image: mysql:5.7
        ports:
            -   "3306:3306"
        volumes:
            -   ./docker/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: hD5rC2ccAq
    adminer:
        image: adminer
        restart: always
        ports:
            - "8081:8080"
